name: Create Jar Files
on: [push]


jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo files
        uses: actions/checkout@v3
        


      - name: Extract all jar files
        run: |
         cd jars
         for file in *.jar; do unzip -d $file.dir $file; done
         cd ..

      - name: Remove the default ROM from all of them and add in CustROM
        run: |
         cd ./jars/cc-tweaked-1.12.2-1.89.2.jar.dir/assets/computercraft/lua/
         rm -r ./rom && rm bios.lua
         cp -R ./../../../../../rom ./rom
         cp -R ./../../../../../bios.lua ./bios.lua
         cd ./../../../../..
         cd ./jars/cc-tweaked-1.13.2-1.83.1.jar.dir/data/computercraft/lua/
         rm -r ./rom && rm bios.lua
         cp -R ./../../../../../rom ./rom
         cp -R ./../../../../../bios.lua ./bios.lua
         cd ./../../../../..
         cd ./jars/cc-tweaked-1.14.4-1.89.2.jar.dir/data/computercraft/lua/
         rm -r ./rom && rm bios.lua
         cp -R ./../../../../../rom ./rom
         cp -R ./../../../../../bios.lua ./bios.lua
         cd ./../../../../..
         cd ./jars/cc-tweaked-1.15.2-1.97.1.jar.dir/data/computercraft/lua/
         rm -r ./rom && rm bios.lua
         cp -R ./../../../../../rom ./rom
         cp -R ./../../../../../bios.lua ./bios.lua
         cd ./../../../../..
         cd ./jars/cc-tweaked-1.16.5-1.100.8.jar.dir/data/computercraft/lua/
         rm -r ./rom && rm bios.lua
         cp -R ./../../../../../rom ./rom
         cp -R ./../../../../../bios.lua ./bios.lua
         cd ./../../../../..
         cd ./jars/cc-tweaked-1.17.1-1.100.4.jar.dir/data/computercraft/lua/
         rm -r ./rom && rm bios.lua
         cp -R ./../../../../../rom ./rom
         cp -R ./../../../../../bios.lua ./bios.lua
         cd ./../../../../..
         cd ./jars/cc-tweaked-1.18.2-1.100.8.jar.dir/data/computercraft/lua/
         rm -r ./rom && rm bios.lua
         cp -R ./../../../../../rom ./rom
         cp -R ./../../../../../bios.lua ./bios.lua
         cd ./../../../..        
      - name: List all files
        run: ls
        
      - name: Remove all jar files and compress the folders into jar files
        run: |
         cd jars
         rm *.jar
         cd cc-tweaked-1.12.2-1.89.2.jar.dir && zip -r cc-tweaked-1.12.2-1.89.2.jar * && mv cc-tweaked-1.12.2-1.89.2.jar ../cc-tweaked-1.12.2-1.89.2-custrom.jar && cd ..
         cd cc-tweaked-1.13.2-1.83.1.jar.dir && zip -r cc-tweaked-1.13.2-1.83.1.jar * && mv cc-tweaked-1.13.2-1.83.1.jar ../cc-tweaked-1.13.2-1.83.1-custrom.jar && cd ..
         cd cc-tweaked-1.14.4-1.89.2.jar.dir && zip -r cc-tweaked-1.14.4-1.89.2.jar * && mv cc-tweaked-1.14.4-1.89.2.jar ../cc-tweaked-1.14.4-1.89.2-custrom.jar && cd ..
         cd cc-tweaked-1.15.2-1.97.1.jar.dir && zip -r cc-tweaked-1.15.2-1.97.1.jar * && mv cc-tweaked-1.15.2-1.97.1.jar ../cc-tweaked-1.15.2-1.97.1-custrom.jar && cd ..
         cd cc-tweaked-1.16.5-1.100.8.jar.dir && zip -r cc-tweaked-1.16.5-1.100.8.jar * && mv cc-tweaked-1.16.5-1.100.8.jar ../cc-tweaked-1.16.5-1.100.8-custrom.jar && cd ..
         cd cc-tweaked-1.17.1-1.100.4.jar.dir && zip -r cc-tweaked-1.17.1-1.100.4.jar * && mv cc-tweaked-1.17.1-1.100.4.jar ../cc-tweaked-1.17.1-1.100.4-custrom.jar && cd ..
         cd cc-tweaked-1.18.2-1.100.8.jar.dir && zip -r cc-tweaked-1.18.2-1.100.8.jar * && mv cc-tweaked-1.18.2-1.100.8.jar ../cc-tweaked-1.18.2-1.100.8-custrom.jar && cd ..
      
      - name: Move all jar files into artifact folder and finish.
        run: cd jars && mkdir artifacts && mv ./*.jar ./artifacts/ && ls
        
      - name: Upload everything.
        uses: actions/upload-artifact@v2
        with:
          name: Jar Files
          path: jar/artifacts/
          
